chore: Change Validatition requirement
equinor/oplog-api pull request #136
Opened 2023-11-27 09:45 UTC by eobrequinor

2023-11-27 09:57 UTC, FredrikMWold requested changes
Does this check for atleast one filter and searchText or two filters?

2023-11-27 10:09 UTC, mikkel1ea commented
#137 Can link the PR to this issue when you're ready.

2023-11-27 10:11 UTC, bonyfusbouvet approved these changes

2023-11-28 07:39 UTC, eobrequinor commented
Feel free to suggest different Error messages

2023-11-28 07:50 UTC, FredrikMWold approved these changes

2023-11-28 08:06 UTC, bonyfusbouvet approved these changes

2023-11-28 08:10 UTC, merged